config/routes.rb
Rails.application.routes.draw do
  resources :rohans
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rohan.rb
class Rohan < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rohans_controller.rb
class RohansController < ApplicationController
  before_action :set_rohan, only: %i[ show edit update destroy ]

  # GET /rohans or /rohans.json
  def index
    @rohans = Rohan.all
  end

  # GET /rohans/1 or /rohans/1.json
  def show
  end

  # GET /rohans/new
  def new
    @rohan = Rohan.new
  end

  # GET /rohans/1/edit
  def edit
  end

  # POST /rohans or /rohans.json
  def create
    @rohan = Rohan.new(rohan_params)

    respond_to do |format|
      if @rohan.save
        format.html { redirect_to rohan_url(@rohan), notice: "Rohan was successfully created." }
        format.json { render :show, status: :created, location: @rohan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @rohan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rohans/1 or /rohans/1.json
  def update
    respond_to do |format|
      if @rohan.update(rohan_params)
        format.html { redirect_to rohan_url(@rohan), notice: "Rohan was successfully updated." }
        format.json { render :show, status: :ok, location: @rohan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @rohan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rohans/1 or /rohans/1.json
  def destroy
    @rohan.destroy

    respond_to do |format|
      format.html { redirect_to rohans_url, notice: "Rohan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rohan
      @rohan = Rohan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def rohan_params
      params.require(:rohan).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rohans_helper.rb
module RohansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Viky</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rohans/_form.html.erb
<%= form_with(model: rohan) do |form| %>
  <% if rohan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rohan.errors.count, "error") %> prohibited this rohan from being saved:</h2>

      <ul>
        <% rohan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.text_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rohans/edit.html.erb
<h1>Editing Rohan</h1>

<%= render 'form', rohan: @rohan %>

<%= link_to 'Show', @rohan %> |
<%= link_to 'Back', rohans_path %>

app/views/rohans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rohans</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rohans.each do |rohan| %>
      <tr>
        <td><%= rohan.name %></td>
        <td><%= rohan.age %></td>
        <td><%= link_to 'Show', rohan %></td>
        <td><%= link_to 'Edit', edit_rohan_path(rohan) %></td>
        <td><%= link_to 'Destroy', rohan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rohan', new_rohan_path %>

app/views/rohans/new.html.erb
<h1>New Rohan</h1>

<%= render 'form', rohan: @rohan %>

<%= link_to 'Back', rohans_path %>

app/views/rohans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rohan.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @rohan.age %>
</p>

<%= link_to 'Edit', edit_rohan_path(@rohan) %> |
<%= link_to 'Back', rohans_path %>